#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

usage() {
    cat <<'EOF'
StormForge — Bash Project Generator

Usage:
  ./stormforge.sh create <ProjectName>
  ./stormforge.sh help

Commands:
  create    Create a new project scaffold
  help      Show this help message
EOF
}
to_script_name() {
    local name="$1"
    echo "$name" | tr '[:upper:]' '[:lower:]'
}
generate_main_script() {
    local project_name="$1"
    local script_name

    script_name="$(to_script_name "$project_name")"

    cat > "$project_name/src/${script_name}.sh" <<EOF
#!/usr/bin/env bash

set -euo pipefail
IFS=\$'\\n\\t'

usage() {
    echo "Usage: ./${script_name}.sh [options]"
    echo ""
    echo "Options:"
    echo " --help  Show this help message and exit"
    echo ""
    echo "Examples:"
    echo " ./${script_name}.sh --help"
    echo " ./${script_name}.sh"
}

log() {
    local level="\$1"
    shift
    echo "[\$(date '+%Y-%m-%d %H:%M:%S')] [\$level] \$*"
}

error() {
    log "ERROR" "\$@" >&2
    exit 1
}

run() {
    log "INFO" "${project_name} starting..."
    # TODO: implement core logic here
}

main() {
    case "\${1:-}" in
    --help|-h)
	usage
	exit 0
	;;
    "")
	run
	;;
    *)
	error "Unknown argument: \$1"
	;;
    esac
}

main "\$@"
EOF

    chmod +x "$project_name/src/${script_name}.sh"
}

generate_readme() {
    local project_name="$1"
    local script_name
    script_name="$(to_script_name "$project_name")"

        cat > "$project_name/README.md" <<EOF
# ${project_name}

a tool generated by StormForge.

## Usage

\`\`\`bash
./src/${script_name}.sh
\`\`\`

## Install

\`\`\`bash
bash install.sh
\`\`\`
EOF
}

generate_install_script() {
    local project_name="$1"
    local script_name
    script_name="$(to_script_name "$project_name")"

    cat > "$project_name/install.sh" <<EOF
    #!/usr/bin/env bash

    set -euo pipefail

    INSTALL_DIR="\$HOME/.local/bin"
    SCRIPT="${script_name}.sh"
    SOURCE_DIR="\$(cd "\$(dirname "\$0")" && pwd)/src"

    echo "[*] Installing ${project_name}..."

    mkdir -p "\$INSTALL_DIR"
    cp "\$SOURCE_DIR/\$SCRIPT" "\$INSTALL_DIR/\$SCRIPT"
    chmod +x "\$INSTALL_DIR/\$SCRIPT"

    echo "[+] Installed to \$INSTALL_DIR/\$SCRIPT"
    echo "[!] Make sure \$INSTALL_DIR is in your PATH"
EOF
    chmod +x "$project_name/install.sh"

}

generate_config() {
    local project_name="$1"
    local script_name
    script_name="$(to_script_name "$project_name")"

    cat > "$project_name/config/${script_name}.conf" <<EOF
    # ${project_name} configuration
    PROJECT_NAME="${project_name}"
    VERSION="0.1.0"
    LOG_LEVEL="INFO"
    LOG_DIR="logs"
EOF

}

generate_gitignore() {

    local project_name="$1"

    cat > "$project_name/.gitignore" <<EOF

# Logs
logs/
*.log

# Config overrides
*.local.conf

# OS files
.DS_Store
Thumbs.db

# Temp files
*.tmp
*.bak

EOF

}

main() {
    local command="${1:-}"
    local project_name="${2:-}"

    case "$command" in
        create)

            if [[ -z "$project_name" ]]; then
                echo "[!] Error: project name is required."
                usage
                exit 1
            fi

            if [[ -d "$project_name" ]]; then
                echo "[!] Error: directory '$project_name' already exists."
                exit 1
            fi

            echo "[*] Creating project: $project_name"

            mkdir -p "$project_name"/{src,docs,tests,logs,config}

            generate_main_script "$project_name"
            generate_readme "$project_name"
            generate_install_script "$project_name"
            generate_config "$project_name"
            generate_gitignore "$project_name"
            echo "[+] Project '$project_name' created successfully."
            ;;
        help|"")
            usage
            ;;
        *)
            echo "[!] Error: unknown command '$command'"
            usage
            exit 1
            ;;
    esac
}

main "$@"
